Added email to owner table and data
ramrod433/Vet-Clinic pull request #5
Opened 2022-07-11 15:08 UTC by ramrod433

- Before performance audit:

> EXPLAIN ANALYZE SELECT * FROM owners where email = 'owner_18327@mail.com';
EXPLAIN ANALYZE SELECT * FROM visits where vets_id = 2;
EXPLAIN ANALYZE SELECT COUNT(*) FROM visits where animals_id = 4;

![image](https://user-images.githubusercontent.com/99402182/178294754-f9dca909-e3d3-4fed-9f89-06aad1e35ef2.png)

![image](https://user-images.githubusercontent.com/99402182/178294835-26b93df7-4c23-4daf-b386-fcaac2db6ba1.png)

![image](https://user-images.githubusercontent.com/99402182/178294885-4523afc6-6dc2-4361-9ea9-d770a7ef2757.png)

- After Optimization

> CREATE INDEX visits_animal_id_idx ON visits(animals_id);
CREATE INDEX visits_vet_id_idx ON visits(vets_id);
CREATE INDEX owners_email_idx ON owners(email);

![image](https://user-images.githubusercontent.com/99402182/178295069-c4256efa-df00-4b57-9d14-cb6daba4400c.png)

![image](https://user-images.githubusercontent.com/99402182/178295137-58354644-9bfe-47aa-a43c-3fa9eefa80ff.png)

![image](https://user-images.githubusercontent.com/99402182/178295270-0fc091f6-c5be-4965-9a71-0fcedec715fe.png)

2022-07-11 15:28 UTC, Mre55 requested changes
Hi @ramrod433,

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 

## Required Changes ♻️🛠️ 

- [x] This task is pair-programming and I see your commit only. Kindly, make sure the change has to be implemented by your partner to make commits even.

_Check the comments under the review._

<img width="430" src="https://media1.giphy.com/media/oVjOd9TEZDmSTc4x37/giphy.gif"/>


## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-11 15:28 UTC, Mre55 commented on data.sql
> +INSERT INTO visits (animal_id, vet_id, date_of_visit) SELECT * FROM (SELECT id FROM animals) animal_ids, (SELECT id FROM vets) vets_ids, generate_series('1980-01-01'::timestamp, '2021-01-01', '4 hour
Kindly, make sure that after introducing index the performance should be improved and the execution time should be less than 1000ms. Please implement proper index for this `SELECT \* FROM visits where vet_id = 2;` query to achieve the execution time less than 1000ms. I noticed it's above 1000ms in your screenshot.

2022-07-12 07:02 UTC, ramrod433 commented on data.sql
> +INSERT INTO visits (animal_id, vet_id, date_of_visit) SELECT * FROM (SELECT id FROM animals) animal_ids, (SELECT id FROM vets) vets_ids, generate_series('1980-01-01'::timestamp, '2021-01-01', '4 hour
Implemented

2022-07-12 07:06 UTC, aimemalaika approved these changes
Hi @ramrod433  & @aimalamiri , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-12 07:10 UTC, merged